#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.superuser = "package_checker"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    # test_upgrade_from.cfc42dd5.name = "Last manifestv1 package"
    test_upgrade_from.1d5d855975e34da71bb3051c9fe2d6c781f6f1e1.name = "Upgrade from 3.4.2~ynh5"
