#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script

TRAP_ON	# Active trap pour arrêter le script si une erreur est détectée.

domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
admin_mopidy=$YNH_APP_ARG_ADMIN_MOPIDY
spotify_user=$YNH_APP_ARG_SPOTIFY_USER
spotify_pass=$YNH_APP_ARG_SPOTIFY_PASS
spotify_id=$YNH_APP_ARG_SPOTIFY_ID
spotify_id_secret=$YNH_APP_ARG_SPOTIFY_ID_SECRET
soundcloud_id=$YNH_APP_ARG_SOUNDCLOUD_ID

app=$YNH_APP_INSTANCE_NAME

# Source app helpers
source /usr/share/yunohost/helpers

CHECK_VAR "$app" "app name not set"

CHECK_USER "$admin_mopidy"

CHECK_DOMAINPATH

CHECK_FINALPATH

ynh_app_setting_set $app domain $domain
ynh_app_setting_set $app path $path
ynh_app_setting_set $app admin $admin_mopidy
if [ -n "$spotify_user" ];
then
	ynh_app_setting_set $app spotify_user $spotify_user
	ynh_app_setting_set $app spotify_pass $spotify_pass
	ynh_app_setting_set $app spotify_id $spotify_id
	ynh_app_setting_set $app spotify_id_secret $spotify_id_secret
fi
if [ -n "$soundcloud_id" ];
then
	ynh_app_setting_set $app soundcloud_id $soundcloud_id
fi

# Create final_path and check
sudo mkdir "$final_path"
sudo chown -R www-data: $final_path
ynh_app_setting_set $app final_path $final_path

# Add the archive’s GPG key:
wget -q -O - https://apt.mopidy.com/mopidy.gpg | sudo apt-key add -

# Add the APT repo to your package sources:
sudo wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/jessie.list

# Install Mopidy and all dependencies:
sudo apt-get update
sudo apt-get install -y mopidy
sudo apt-get install -y mopidy-soundcloud
sudo apt-get install -y mopidy-spotify

# Copy configuration
ip_local=$(hostname -I | awk '{ print $1 }')
sudo sed -i "s@__IPLOCAL__@$ip_local@g" ../conf/mopidy.conf

if [ -n "$spotify_user" ];
then
	sudo sed -i '/\[spotify\]/a enabled = true' ../conf/mopidy.conf
	sudo sed -i "s@__USER_SPOTIFY__@$spotify_user@g" ../conf/mopidy.conf
	sudo sed -i "s@__PWD_SPOTIFY__@$spotify_pass@g" ../conf/mopidy.conf
	sudo sed -i "s@__ID_SPOTIFY__@$spotify_id@g" ../conf/mopidy.conf
	sudo sed -i "s@__SECRET_SPOTIFY__@$spotify_id_secret@g" ../conf/mopidy.conf
else
	sudo sed -i '/\[spotify\]/a enabled = false' ../conf/mopidy.conf
	sudo sed -i "s@__USER_SPOTIFY__@@g" ../conf/mopidy.conf
	sudo sed -i "s@__PWD_SPOTIFY__@@g" ../conf/mopidy.conf
	sudo sed -i "s@__ID_SPOTIFY__@@g" ../conf/mopidy.conf
	sudo sed -i "s@__SECRET_SPOTIFY__@@g" ../conf/mopidy.conf
fi

if [ -n "$soundcloud_id" ];
then
	sudo sed -i "s@__SOUNDCLOUD__@$soundcloud_id@g" ../conf/mopidy.conf
else
	sudo sed -i "s@__SOUNDCLOUD__@@g" ../conf/mopidy.conf
fi

# Copy config nginx
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Change file configuration for nginx
sudo sed -i "s@__PATHTOCHANGE__@$path@g" /etc/nginx/conf.d/$domain.d/$app.conf
sudo sed -i "s@__DOMAINNAME__@$domain@g" /etc/nginx/conf.d/$domain.d/$app.conf
sudo sed -i "s@__FINALPATH__@$final_path@g" /etc/nginx/conf.d/$domain.d/$app.conf

# Install index.html but it's not necessary
sudo cp ../conf/index.html $final_path
sudo sed -i "s@__DOMAINNAME__@$domain@g" /etc/nginx/conf.d/$domain.d/$app.conf

# Check permission for $final_path
sudo chown -R www-data $final_path

# Copy config mopidy
sudo cp ../conf/mopidy.conf /usr/share/mopidy/conf.d/
sudo mkdir /root/.config/mopidy
# File required for command line 'mopidy local scan'
sudo cp ../conf/mopidy.conf /root/.config/mopidy/
# Copy music file for the test
sudo cp ../conf/Tryad_Beauty.mp3 /var/lib/mopidy/media

# Running Mopidy as a service
sudo mopidy local scan
sudo systemctl enable mopidy
sudo systemctl restart mopidy
sudo systemctl status mopidy

# Copy library.json 
sudo cp /root/.local/share/mopidy/local/library.json.gz /var/lib/mopidy/local/

# Running Mopidy again
sudo systemctl restart mopidy
sudo systemctl status mopidy

# Delete directory and file mopidy configuration
# Mopidy create this directory after install
# but this files create a conflit with a mopidy configuration.
sudo rm -fr /root/.cache/mopidy
sudo rm -fr /root/.config/mopidy
sudo rm -fr /root/.local/share/mopidy

## Install mopidy-musicbox-webclient
cd /tmp/
sudo git clone https://github.com/pimusicbox/mopidy-musicbox-webclient
cd mopidy-musicbox-webclient
sudo python setup.py install

# Allow port 
sudo yunohost firewall allow TCP 6600
sudo yunohost firewall allow TCP 6680

# Access public for curl
ynh_app_setting_set $app unprotected_uris "/"

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload

# Add Mopidy into YunoHost services
sudo yunohost service add mopidy --log "/var/log/mopidy/mopidy.log"

# Reload SSOwat configuration
sudo yunohost app ssowatconf