#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -u

source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script

# Source app helpers
source /usr/share/yunohost/helpers

# Get application informations
app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get $app domain)

# Remove application
sudo apt-get remove --purge -y mopidy
sleep 4
sudo pip uninstall mopidy_musicbox_webclient
sleep 4

# Delete stupid file
# SECURE_REMOVE '/root/.config/mopidy'
# SECURE_REMOVE '/root/.cache/mopidy'
# SECURE_REMOVE '/root/.local/share/mopidy'
SECURE_REMOVE '/usr/local/bin/mopidy'
SECURE_REMOVE '/usr/share/mopidy'
SECURE_REMOVE '/var/lib/mopidy'
SECURE_REMOVE '/etc/apt/sources.list.d/mopidy.list'
SECURE_REMOVE '/usr/local/lib/python2.7/dist-packages/Mopidy_MusicBox_Webclient-2.3.0-py2.7.egg'
SECURE_REMOVE '/tmp/mopidy-musicbox-webclient'
SECURE_REMOVE '/var/www/$app'

# disallow firewall port
sudo yunohost firewall disallow TCP 6600
sudo yunohost firewall disallow TCP 6680

REMOVE_NGINX_CONF	# Suppression de la configuration nginx

# Régénère la configuration de SSOwat
sudo yunohost app ssowatconf

echo -e "\e[0m"	# Restore normal color