#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -u

source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script

# Source app helpers
source /usr/share/yunohost/helpers

# Get application informations
app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get $app domain)

# Remove application
sudo apt-get remove --purge -y mopidy
sudo apt-get remove --purge -y mopidy-soundcloud
sudo apt-get remove --purge -y mopidy-spotify
sleep 4
sudo pip uninstall -y mopidy_musicbox_webclient
sleep 4

# Delete stupid file
# Normally a root directory is delete with install app
if [ -d "/root/.config/$app" ]; then
	SECURE_REMOVE '/root/.config/$app'
fi
if [ -d "/root/.cache/$app" ]; then
	SECURE_REMOVE '/root/.cache/$app'
fi
if [ -d "/root/.local/share/$app" ]; then
	SECURE_REMOVE '/root/.local/share/$app'
fi

SECURE_REMOVE '/usr/local/bin/$app'
SECURE_REMOVE '/usr/share/$app'
SECURE_REMOVE '/var/lib/$app'
SECURE_REMOVE '/etc/apt/sources.list.d/$app.list'
SECURE_REMOVE '/tmp/$app-musicbox-webclient'
SECURE_REMOVE '/var/www/$app'
sudo rm -fr '/usr/local/lib/python2.7/dist-packages/Mopidy_MusicBox_Webclient-2.3.0-py2.7.egg'

# disallow firewall port
sudo yunohost firewall disallow TCP 6600
sudo yunohost firewall disallow TCP 6680

REMOVE_NGINX_CONF	# Suppression de la configuration nginx

# Régénère la configuration de SSOwat
sudo yunohost app ssowatconf

echo -e "\e[0m"	# Restore normal color