#!/bin/bash
# This restore script is adapted to Yunohost >=2.4

# Exit on command errors and treat unset variables as an error
set -eu

# The parameter $1 is the backup directory location dedicated to the app
backup_dir=$1

# The parameter $2 is the id of the app instance ex: ynhexample__2
app=$YNH_APP_INSTANCE_NAME

# Source app helpers
source /usr/share/yunohost/helpers

# Get old parameter of the app
domain=$(ynh_app_setting_get $app domain)
path=$(ynh_app_setting_get $app path)
final_path=$(ynh_app_setting_get $app final_path)

if [ -d $final_path ]; then
    ynh_die "There is already a directory: $final_path"
fi

conf=/etc/nginx/conf.d/$domain.d/$app.conf
if [ -f $conf ]; then
    ynh_die "There is already a nginx conf file at this path: $conf"
fi
# Restore conf files
sudo cp -a "${backup_dir}/conf/nginx.conf" $conf

# Reload Nginx
sudo service nginx reload

sudo cp -a "${backup_dir}/var/www/$app" $final_path
sudo cp -a "${backup_dir}/var/lib/$app" "/var/lib/$app"

# Set permissions
sudo chown -R www-data: $final_path

# Restart service and add service into YunoHost
sudo service mopidy restart
sudo yunohost service add mopidy --log "/var/log/mopidy/mopidy.log"

sudo yunohost app ssowatconf
