#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_safe_rm "$install_dir/env"

# Legacy settings
if [ -n "${mpd_port:-}" ]; then
    if [ "$mpd_port" -eq 0 ]; then
        mpd_ext=0
    else
        mpd_ext=1
    fi
    ynh_app_setting_set --key=mpd_ext --value="$mpd_ext"
    ynh_app_setting_delete --key=mpd_port
fi

if [ -z "${mpd_state:-}" ]; then
    mpd_state="${boolstr[mpd_ext]}"
    ynh_app_setting_set --key=mpd_state --value="$mpd_state"
fi

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

_mopidy_install

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template="app.conf" --destination="$install_dir/$app.conf"

chmod 400 "$install_dir/$app.conf"
chown "$app:$app" "$install_dir/$app.conf"

#=================================================
# PROVIDE ADDITIONAL SHELL COMMAND
#=================================================
ynh_script_progression "Provide additional shell comand..."

ynh_config_add --template="../sources/extra_files/mopidyctl" --destination="$cmd_file"
chmod +x "$cmd_file"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
if [ "$mpd_ext" -eq 1 ]; then
    yunohost service add "$app" --description="Mopidy music server" --needs_exposed_ports="$port_mpd"
else
    yunohost service add "$app" --description="Mopidy music server"
fi

#=================================================
# OPEN PORT
#=================================================
if [ "$mpd_ext" -eq 1 ]; then
    ynh_script_progression "Opening MPD-port $port_mpd..."
    ynh_hide_warnings yunohost firewall allow --no-upnp TCP "$port_mpd"
fi

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
